- name: etcd
  hosts: all
  gather_facts: false
  become: true
  roles:
    - etcd
  tags:
    - etcd

# - name: openshift-master servers
#   hosts: openshift-master
#   gather_facts: false
#   become: true
#   roles:
#     - openshift-master
#   tags:
#     - openshift-master
#
# - name: openshift-node servers
#   hosts: openshift-node
#   gather_facts: false
#   become: true
#   roles:
#     - openshift-node
#   tags:
#     - openshift-node
