- name: openshift-master servers
  hosts: openshift-master
  gather_facts: false
  sudo: true
  roles:
    - openshift-master
  tags:
    - openshift-master

- name: openshift-node servers
  hosts: openshift-node
  gather_facts: false
  sudo: true
  roles:
    - openshift-node
  tags:
    - openshift-node
