- name: install etcd config
  template:
    src: etcd.conf
    dest: /etc/etcd/etcd.conf
  notify: restart etcd

- name: start and enable etcd-docker
  service:
    name: etcd
    state: started
    enabled: yes
  register: start_result

- set_fact:
    etcd_service_status_changed: "{{ start_result | changed }}"
