- name: create openshift-master config directory
  file:
    path: "{{ openshift_master_config_dir }}"
    state: directory

- name: install ca root certificate set
  copy:
    src: "{{ item.file }}"
    dest: "{{ openshift_master_config_dir }}/{{ item.file }}"
    mode: "{{ item.mode }}"
    force: "{{ item.force | default(true) }}"
  with_items:
    - file: ca.crt
      mode: '0644'
    - file: ca.key
      mode: '0600'
    - file: ca.serial.txt
      mode: '0644'
      force: false

- name: create the master certificates
  command: >
    {{ openshift_admin_binary }} ca create-master-certs
      --hostnames={{ private_ip }},{{ openshift_kubernetes_service_ip }},openshift-master.skydns.local
      --master=https://{{ private_ip }}:8443
      --public-master=https://{{ private_ip }}:8443
      --cert-dir={{ openshift_master_config_dir }}
  args:
    creates: "{{ openshift_master_config_dir }}/master.server.crt"

- name: create the policy file
  command: "{{ openshift_admin_binary }} create-bootstrap-policy-file"
  args:
    creates: "{{ openshift_master_config_dir }}/policy.json"

- name: symlink the admin kubeconfig to /root/.kube/config
  file:
    src: "{{ openshift_master_config_dir }}/admin.kubeconfig"
    dest: /root/.kube/config
    state: link

- name: install openshift-master config
  template:
    src: master-config.yaml
    dest: "{{ openshift_master_config_dir }}/master-config.yaml"
  notify: restart openshift-master

- name: install openshift-master service
  template:
    src: openshift-master.service
    dest: /etc/systemd/system/openshift-master.service
  notify: restart openshift-master
  register: openshift_master_service

- name: reload service files
  command: systemctl daemon-reload
  when: openshift_master_service.changed

- name: start and enable openshift-master
  service: name=openshift-master state=started enabled=yes
  register: start_result

- set_fact:
    openshift_master_service_status_changed: "{{ start_result | changed }}"
