openshift_origin_version: v1.1.4
openshift_master_api_url: https://{{ hostvars[groups['openshift-master'][0]]['private_ip'] }}:8443

openshift_binary_path: /usr/local/sbin
openshift_binary: "{{ openshift_binary_path }}/openshift"
openshift_admin_binary: "{{ openshift_binary_path }}/oadm"
openshift_client_binary: "{{ openshift_binary_path }}/oc"
openshift_kubectl_binary: "{{ openshift_binary_path }}/kubectl"

openshift_master_config_path: /etc/origin/master
openshift_pod_manifest_path: /etc/origin/node/manifests

openshift_cluster_subnet: 10.2.0.0/16
openshift_cluster_subnet_first_two_octets: '10.2'
openshift_service_subnet: 10.3.0.0/24
openshift_kubernetes_service_ip: 10.3.0.1

openshift_dns_domain: cluster.local
openshift_external_dns_domain: "{{ hostvars[groups['openshift-master'][0]]['private_ip'] }}.xip.io"

openshift_metrics_hostname: hawkular-metrics.{{ openshift_external_dns_domain }}
openshift_metrics_public_url: https://{{ openshift_metrics_hostname }}/hawkular/metrics
