container_mount: /host
ansible_python_interpreter: /opt/bin/python

openshift_origin_version: v1.1.2
openshift_master_api_url: https://{{ hostvars[groups['openshift-master'][0]]['private_ip'] }}:8443
