openshift_origin_version: v1.1.4
openshift_master_api_url: https://{{ hostvars[groups['openshift-master'][0]]['private_ip'] }}:8443

openshift_binary: /usr/local/sbin/openshift
openshift_admin_binary: /usr/local/sbin/oadm
openshift_client_binary: /usr/local/sbin/oc
openshift_kubectl_binary: /usr/local/sbin/kubectl

openshift_pod_manifest_path: /etc/origin/node/manifests
openshift_master_config_dir: /var/lib/origin/openshift.local.config/master

openshift_cluster_subnet: 10.2.0.0/16
openshift_cluster_subnet_first_two_octets: '10.2'
openshift_service_subnet: 10.3.0.0/24
openshift_kubernetes_service_ip: 10.3.0.1

openshift_dns_domain: "{{ hostvars[groups['openshift-master'][0]]['private_ip'] }}.xip.io"
