openshift_origin_version: v1.1.3
openshift_master_api_url: https://{{ hostvars[groups['openshift-master'][0]]['private_ip'] }}:8443

openshift_binary: /usr/local/sbin/openshift
openshift_admin_binary: /usr/local/sbin/oadm
openshift_client_binary: /usr/local/sbin/oc
openshift_kubectl_binary: /usr/local/sbin/kubectl

openshift_pod_manifest_path: /etc/origin/node/manifests
