#cloud-config
coreos:
  update:
    reboot-strategy: off
  etcd2:
    name: coreos-01
    initial-cluster: coreos-01=http://192.168.8.201:2380
    advertise-client-urls: http://$public_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://$private_ipv4:2380
  fleet:
    public-ip: $public_ipv4
    metadata: kube-apiserver=service,kubelet=service,kube-proxy=service
  flannel:
    interface: $public_ipv4
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.2.0.0/16","Backend":{"Type":"vxlan"}}'
    - name: docker.service
      command: start
      drop-ins:
        - name: 40-flannel.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
users:
  - name: core
    passwd: core

write_files:
  - path: /etc/hosts
    owner: root
    content: |
      172.18.117.71  docker-registry
  - path: /etc/resolv.conf
    owner: root
    content: |
      nameserver 127.0.0.1
      nameserver 10.0.2.3
  - path: /opt/bin/python
    permissions: '0755'
    owner: root
    content: |
      #!/bin/bash
      if [ ! -d ~/.kube ]; then
         mkdir -m 0700 ~/.kube
      fi
      cmd=`basename $0`
      user=`id -u`
      group=`id -g`

      docker run -it \
        --privileged --net=host --rm \
        -v /:/host \
        -v /home:/home \
        -v /var/lib/origin:/var/lib/origin \
        -v ~/.kube:/root/.kube \
        -v /tmp:/tmp \
        -e KUBECONFIG=/root/.kube/config \
        --entrypoint /usr/bin/python \
        openshift/origin "$@"
  - path: /opt/bin/openshift
    permissions: '0755'
    content: |
      #!/bin/bash
      if [ ! -d ~/.kube ]; then
         mkdir -m 0700 ~/.kube
      fi
      cmd=`basename $0`
      user=`id -u`
      group=`id -g`

      docker run -it \
        --privileged --net=host --rm \
        --user=${user}:${group} \
        -v /var/lib/origin:/var/lib/origin \
        -v ~/.kube:/root/.kube \
        -v /tmp:/tmp \
        -e KUBECONFIG=/root/.kube/config \
        --entrypoint ${cmd} \
        openshift/origin "${@}"
  - path: /root/.toolboxrc
    owner: root
    content: |
      TOOLBOX_DOCKER_IMAGE=allen13/coreos-ansible-toolbox
      TOOLBOX_DOCKER_TAG=latest
      TOOLBOX_USER=root
  - path: /home/core/.toolboxrc
    owner: core
    content: |
      TOOLBOX_DOCKER_IMAGE=allen13/coreos-ansible-toolbox
      TOOLBOX_DOCKER_TAG=latest
      TOOLBOX_USER=root
