apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
spec:
  selector:
    name: mysql
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
  externalIPs:
    - 192.168.8.201
