- name: create openshift-node config directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/lib/origin/openshift.local.config/node
    - /etc/origin/node/

- name: install ca root certificate set
  copy:
    src: "roles/openshift-master/files/{{ item.file }}"
    dest: /var/lib/origin/openshift.local.config/node/{{ item.file }}
    mode: "{{ item.mode }}"
    force: "{{ item.force | default(true) }}"
  with_items:
    - file: ca.crt
      mode: '0644'
    - file: ca.key
      mode: '0600'
    - file: ca.serial.txt
      mode: '0644'
      force: false

- name: generate the node client config
  command: >
    {{ openshift_admin_binary }} create-api-client-config
      --certificate-authority=/var/lib/origin/openshift.local.config/node/ca.crt
      --client-dir=/var/lib/origin/openshift.local.config/node/
      --groups=system:nodes
      --master={{ openshift_master_api_url }}
      --signer-cert=/var/lib/origin/openshift.local.config/node/ca.crt
      --signer-key=/var/lib/origin/openshift.local.config/node/ca.key
      --signer-serial=/var/lib/origin/openshift.local.config/node/ca.serial.txt
      --user=system:node:{{ inventory_hostname }}
  args:
    creates: /var/lib/origin/openshift.local.config/node/system:node:{{ inventory_hostname }}.crt

- name: generate the node server certificate
  command: >
    {{ openshift_admin_binary }} ca create-server-cert
      --cert=/var/lib/origin/openshift.local.config/node/server.crt
      --key=/var/lib/origin/openshift.local.config/node/server.key
      --hostnames="{{ private_ip }},{{ inventory_hostname }}"
      --signer-cert=/var/lib/origin/openshift.local.config/node/ca.crt
      --signer-key=/var/lib/origin/openshift.local.config/node/ca.key
      --signer-serial=/var/lib/origin/openshift.local.config/node/ca.serial.txt
  args:
    creates: /var/lib/origin/openshift.local.config/node/server.crt

- name: install openshift-node config
  template:
    src: node-config.yaml
    dest: /etc/origin/node/node-config.yaml
  notify: restart openshift-node

- name: wait for openshift master
  command: curl -k --head --silent {{ openshift_master_api_url }}
  register: api_available_output
  until: api_available_output.stdout.find("200 OK") != -1
  retries: 120
  delay: 1
  changed_when: false

- name: install openshift-node service
  template:
    src: openshift-node.service
    dest: /etc/systemd/system/openshift-node.service
  register: openshift_node_service
  notify: restart openshift-node

- name: reload service files
  command: systemctl daemon-reload
  when: openshift_node_service.changed

- name: start and enable openshift-node
  service: name=openshift-node state=started enabled=yes
  register: start_result

- set_fact:
    openshift_node_service_status_changed: "{{ start_result | changed }}"
