- name: create openshift-node config directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ openshift_node_config_path }}"

- name: install ca root certificate set
  copy:
    src: "roles/openshift-master/files/{{ item.file }}"
    dest: "{{ openshift_node_config_path }}/{{ item.file }}"
    mode: "{{ item.mode }}"
    force: "{{ item.force | default(true) }}"
  with_items:
    - file: ca.crt
      mode: '0644'
    - file: ca.key
      mode: '0600'
    - file: ca.serial.txt
      mode: '0644'
      force: false

- name: generate the node client config
  command: >
    {{ openshift_admin_binary }} create-api-client-config
      --certificate-authority={{ openshift_node_config_path }}/ca.crt
      --client-dir={{ openshift_node_config_path }}
      --groups=system:nodes
      --master={{ openshift_master_api_url }}
      --signer-cert={{ openshift_node_config_path }}/ca.crt
      --signer-key={{ openshift_node_config_path }}/ca.key
      --signer-serial={{ openshift_node_config_path }}/ca.serial.txt
      --user=system:node:{{ inventory_hostname }}
  args:
    creates: "{{ openshift_node_config_path }}/system:node:{{ inventory_hostname }}.crt"

- name: generate the node server certificate
  command: >
    {{ openshift_admin_binary }} ca create-server-cert
      --cert={{ openshift_node_config_path }}/server.crt
      --key={{ openshift_node_config_path }}/server.key
      --hostnames="{{ private_ip }},{{ inventory_hostname }}"
      --signer-cert={{ openshift_node_config_path }}/ca.crt
      --signer-key={{ openshift_node_config_path }}/ca.key
      --signer-serial={{ openshift_node_config_path }}/ca.serial.txt
  args:
    creates: "{{ openshift_node_config_path }}/server.crt"

- name: ensure manifests directory is present
  file:
    path: '{{ openshift_pod_manifest_path }}'
    state: directory
    mode: 0755

- name: install dummy container that sleeps then exits to prevent failure from empty manifests
  copy:
    src: alpine.yml
    dest: '{{ openshift_pod_manifest_path }}/alpine.yml'

- name: install openshift-node config
  template:
    src: node-config.yaml
    dest: "{{ openshift_node_config_path }}/node-config.yaml"
  notify: restart openshift-node

- name: install openshift-node sysconfig
  template:
    src: openshift-node.sysconfig
    dest: /etc/sysconfig/openshift-node
  notify: restart openshift-node

- name: wait for openshift master
  command: curl -k --head --silent {{ openshift_master_api_url }}
  register: api_available_output
  until: api_available_output.stdout.find("200 OK") != -1
  retries: 120
  delay: 1
  changed_when: false

- name: install openshift-node service
  template:
    src: openshift-node.service
    dest: /etc/systemd/system/openshift-node.service
  register: openshift_node_service
  notify: restart openshift-node

- name: reload service files
  command: systemctl daemon-reload
  when: openshift_node_service.changed

- name: start and enable openshift-node
  service: name=openshift-node state=started enabled=yes
  register: start_result

- set_fact:
    openshift_node_service_status_changed: "{{ start_result | changed }}"
