- name: create {{ openshift_binary }} cli wrapper
  template:
    src: openshift
    dest: "{{ openshift_binary }}"
    mode: 0755

- name: create client symlinks
  file:
    path: "{{ item }}"
    state: link
    src: "{{ openshift_binary }}"
  with_items:
    - "{{ openshift_admin_binary }}"
    - "{{ openshift_client_binary }}"
    - "{{ openshift_kubectl_binary }}"

- name: pull cli image
  command: docker pull openshift/origin:{{ openshift_origin_version }}
  register: openshift_image_pull
  changed_when: "'Image is up to date' not in openshift_image_pull.stdout"
