- name: create {{ openshift_binary }} cli wrapper
  template:
    src: openshift
    dest: "{{ openshift_binary }}"
    mode: 0755

- name: create client symlinks
  file:
    path: "{{ item }}"
    state: link
    src: "{{ openshift_binary }}"
  with_items:
    - "{{ openshift_admin_binary }}"
    - "{{ openshift_client_binary }}"
    - "{{ openshift_kubectl_binary }}"
