apiVersion: v1
kind: Pod
metadata:
  name: metrics-deployer
  labels:
    component: deployer
    metrics-infra: deployer
    provider: openshift
spec:
  containers:
  - env:
    - name: PROJECT
      value: openshift-infra
    - name: IMAGE_PREFIX
      value: openshift/origin-
    - name: IMAGE_VERSION
      value: latest
    - name: MASTER_URL
      value: https://kubernetes.default.svc.{{ openshift_dns_domain }}
    - name: REDEPLOY
      value: 'false'
    - name: MODE
      value: deploy
    - name: USE_PERSISTENT_STORAGE
      value: 'false'
    - name: HAWKULAR_METRICS_HOSTNAME
      value: {{ openshift_metrics_hostname }}
    - name: CASSANDRA_NODES
      value: '1'
    - name: CASSANDRA_PV_SIZE
      value: 10Gi
    # - name: METRIC_DURATION
    #   value: '7'
    image: openshift/origin-metrics-deployer:latest
    name: deployer
    volumeMounts:
    - mountPath: /secret
      name: secret
      readOnly: true
    - mountPath: /etc/deploy
      name: empty
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  serviceAccount: metrics-deployer
  volumes:
  - emptyDir: {}
    name: empty
  - name: secret
    secret:
      secretName: metrics-deployer
