- name: deploy openshift registry
  command: >
    {{ openshift_admin_binary }} registry
  register: openshift_registry_results
  changed_when: "'service exists' not in openshift_registry_results.stdout"
