etcd_image: quay.io/coreos/etcd
etcd_image_version: v2.2.5

etcd_initial_cluster: "{{ hostvars | get_etcd_cluster(groups['etcd']) | join(',') }}"
etcd_initial_cluster_token: etcd-cluster
etcd_proxy: "{{ 'off' if inventory_hostname in groups['etcd'] else 'on'}}"
