apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: 'true'
    version: v10
  name: heapster-v10
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v10
  template:
    metadata:
      labels:
        k8s-app: heapster
        kubernetes.io/cluster-service: 'true'
        version: v10
    spec:
      containers:
      - command:
        - /heapster
        - --source=kubernetes:''
        - --sink=influxdb:http://monitoring-influxdb:8086
        - --stats_resolution=30s
        - --sink_frequency=1m
        image: gcr.io/google_containers/heapster:v0.18.2
        name: heapster
        resources:
          limits:
            cpu: 100m
            memory: 212Mi
          requests:
            cpu: 100m
            memory: 212Mi
