apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: influxdb
    kubernetes.io/cluster-service: 'true'
    version: v2
  name: monitoring-influxdb-v2
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: influxdb
    version: v2
  template:
    metadata:
      labels:
        k8s-app: influxdb
        kubernetes.io/cluster-service: 'true'
        version: v2
    spec:
      containers:
      - image: gcr.io/google_containers/heapster_influxdb:v0.4
        name: influxdb
        ports:
        - containerPort: 8083
          hostPort: 8083
        - containerPort: 8086
          hostPort: 8086
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /data
          name: influxdb-persistent-storage
      volumes:
      - emptyDir: {}
        name: influxdb-persistent-storage
