allowDisabledDocker: false
apiVersion: v1
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: 5m
  authorizationCacheSize: 1000
  authorizationCacheTTL: 5m
dnsDomain: {{ openshift_dns_domain }}
dnsIP: {{ openshift_kubernetes_service_ip }}
dockerConfig:
  execHandlerName: native
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
iptablesSyncPeriod: 5s
kind: NodeConfig
masterKubeConfig: /var/lib/origin/openshift.local.config/node/system:node:{{ inventory_hostname }}.kubeconfig
networkConfig:
  mtu: 1450
  networkPluginName: ""
nodeIP: {{ private_ip }}
nodeName: {{ private_ip }}
podManifestConfig:
  path: {{ openshift_pod_manifest_path }}
  fileCheckIntervalSeconds: 10
servingInfo:
  bindAddress: 0.0.0.0:10250
  bindNetwork: tcp4
  certFile: /var/lib/origin/openshift.local.config/node/server.crt
  clientCA: /var/lib/origin/openshift.local.config/node/system:node:{{ inventory_hostname }}.crt
  keyFile: /var/lib/origin/openshift.local.config/node/server.key
  namedCertificates: null
volumeDirectory: /var/lib/origin/openshift.local.volumes
